title: Stuart McHattie | IsCoding
description: "Stuart McHattie: Software Engineer & Solution Architect"
favicon: "/fav.png"

# Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
mathjax: false

# Whether the fade animations on the home page will be enabled
animate: true

theme:
  # disableThemeToggle: true
  # defaultTheme: "light" # dark

font:
  fontSize: 1rem # default: 1rem
  fontWeight: 400 # default: 400
  lineHeight: 1.5 # default: 1.5
  textAlign: left # default: left

# Colour Preferences
# When using hex codes for colors, quotations must be used along with the # sign
color:
  textColor: "#343a40"
  secondaryTextColor: "#6c757d"
  textLinkColor: "#449d1d"
  backgroundColor: "#eaedf0"
  secondaryBackgroundColor: "#64ffda1a"
  primaryColor: "#2b7f07"
  secondaryColor: "#f8f9fa"

#   darkmode:
#     textColor: "#e4e6eb"
#     secondaryTextColor: "#b0b3b8"
#     textLinkColor: "#ffffff"
#     backgroundColor: "#18191a"
#     secondaryBackgroundColor: "#212529"
#     primaryColor: "#ffffff"
#     secondaryColor: "#212529"

# If you want to customize the menu, you can change it here
navbar:
  align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  # showBrandLogo: false # Show brand logo in nav bar | default is true
  brandName: IsCoding # Brand name for the brand | default is the title variable
  disableSearch: false
  # searchPlaceholder: "Search"
  stickyNavBar:
    enable: false
    showOnScrollUp: true
  enableSeparator: true
  menus:
    disableAbout: false
    disableExperience: false
    disableEducation: true
    disableProjects: false
    disableAchievements: false
    disableContact: false

# Hero
hero:
  enable: true
  intro: Hi, my name is
  title: Stuart McHattie.
  subtitle: I bring software to life!
  content: |-
    I'm a senior software engineer and solution architect in Oxfordshire, UK.

    I've been designing, implementing, deploying and supporting software professionally since 2011, but I've written code since the late 1980s.
    I'm also an experienced technical team lead, and have previously been [certified by AWS](https://cp.certmetrics.com/amazon/en/public/verify/credential/PECRMDKK52RQ1PWK) as a Solutions Architect: Associate.

    On this site, I write about my experience, my hobbies, my knowledge, and any other thoughts I may have.
    If you find anything interesting here, please do [get in touch](#contact) as it makes me very happy to discuss and share.
  image: /images/avatar.jpg
  bottomImage:
    enable: true
  # roundImage: true # Make hero image circular | default false
  button:
    enable: false
    name: CV
    url: "#"
    download: true
    newPage: false
  socialLinks:
    fontAwesomeIcons:
      - icon: fab fa-github
        url: https://github.com/sdjmchattie/
      - icon: fab fa-linkedin
        url: http://linkedin.com/in/stuart-m-53269467
      - icon: fab fa-mastodon
        url: https://hachyderm.io/@sdjmchattie
      - icon: fab fa-stack-overflow
        url: https://stackoverflow.com/users/772095/sdjmchattie
  #   customIcons:
  #     - icon: /fav.png
  #       url: "https://example.com"

# About
about:
  enable: true
  title: "About Me"
  image: "/images/about-me-photo.jpg"
  content: |-
    I live and love software!
    I was born in Kent in the early 1980s and was fascinated by electronics of the time.
    Growing up, I learned how to write code for computers like the ZX Spectrum 128k +2.
    As I went through my education, my skills adapted to Microsoft Visual Basic and then Java.

    However, despite all the above, I actually followed an education in biology, gaining my undergraduate degree in Zoology, a masters in Bioinformatics, and finally a combined masters and PhD in Systems Biology at the University of Warwick.
    I have been in my first career job since 2011 where I have grown into a technical team lead and a solution architect.
    I work with clients to determine their requirements and I design solutions that solve their business needs.

    My primary interests in software development revolve around enabling the team to work smoothly and improving user experience so that the solution is loved by the end users.
    I have a large number of years experience in mobile app development and the services the app needs to function, and I have a particular passion for this type of development.

    In my downtime I enjoy photography; reading fact and fiction books; electronics design and repair; as well as playing video games.
  skills:
    enable: true
    title: "Here are a few technologies I've been working with recently:"
    items:
      - Python
      - Ruby
      - Azure
      - LangGraph
      - Docker
      - Agentic AI

# Experience
experience:
  enable: true
  # title: Custom Name
  items:
    - job: Senior Software Engineer
      company: Capgemini Engineering
      companyUrl: https://www.capgemini.com
      date: September 2011 - Present
      featuredLink:
        enable: false
        name: "View the project"
        url: "https://example.com"
      info:
        enable: true
        content: The company I joined in 2011 was called Tessella, but it was acquired by Capgemini in 2022
      content: |-
        I've spent the past 14+ years building my reputation as a professional software engineer in Oxford, UK.
        During my time with the company, I've developed into a technical team lead and a solution architect.
        I've been involved in dozens of projects for dozens of clients, becoming sought after by stakeholders when they need a competent engineer to coordinate their complex requirements.

# Education
education:
  enable: true
  # title: "Custom Name"
  index: false
  items:
    - title: PhD Systems Biology
      school:
        name: University of Warwick
        url: https://warwick.ac.uk
      date: 2006 - 2011
      content: |-
        I studied a combined masters and PhD in Systems Biology.
        My research project was on the gene-expression networks involved in the natural aging of plants.
        I was able to identify and verify at least one unknown interaction between genes involved in this process.

        During this time, I developed an open source software package for R which helps to identify the correlations in microarray data.
        I used the data from those analyses to fit mathematical models for the expression data and used those to highlight candidate gene interactions.
        Experimental proof for the candidate interactions was gathered using techniques such as Yeast-2-Hybrid.
      featuredLink:
        enable: true
        name: "My PhD Thesis"
        url: "https://wrap.warwick.ac.uk/id/eprint/45731/"
    - title: MSc Bioinformatics
      school:
        name: De Montfort University
        url: https://www.dmu.ac.uk/home.aspx
      date: 2003 - 2004
      content: |-
        Following my success analysing data for my BSc, I moved to Leicester to study Bioinformatics at a masters level.
        I achieved a distinction in this degree.
    - title: BSc Zoology
      school:
        name: University of Liverpool
        url: https://www.liverpool.ac.uk
      date: 2000 - 2003
      content: |-
        During my final project, I demonstrated my strength in software development by completing analysis of a research project's data set in 3 weeks which had taken the supervising professor months to analyse due to inefficient processes.

# Achievements
achievements:
  enable: true
  # title: "Custom Name"
  items:
    - title: "Previously Certified AWS Solutions Architect: Associate"
      content: |-
        I took the exam for this certification in December 2022 and scored 846 out of 1000.
        A score of 720 or more constitutes a pass.
      url: https://cp.certmetrics.com/amazon/en/public/verify/credential/PECRMDKK52RQ1PWK
      image: /images/aws-solutions-architect-associate.jpg

# projects
projects:
  enable: false
  # title: "Custom Name"
  items:
    - title: Hugo Profile
      content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
      image: /images/projects/profile.png
      featured:
        name: Demo
        link: https://hugo-profile.netlify.app
      badges:
        - "Hugo"
        - "Bootstrap"
        - "Javascript"
      links:
        - icon: fa fa-envelope
          url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
        - icon: fab fa-github
          url: https://github.com/gurusabarish/hugo-profile
        - icon: fab fa-twitter
          url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

    - title: Image Converter
      content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
      image: /images/projects/converter.jpg
      featured:
        name: Demo
        link: https://django-converter.herokuapp.com
      badges:
        - "Django"
        - "Bootstrap"
      links:
        - icon: fab fa-github
          url: https://github.com/gurusabarish/converter

    - title: Hugo Profile V2
      content: A clean and simple Hugo template for personal portfolio and blog.
      image: /images/projects/profile2.jpg
      featured:
        name: Demo V2
        link: https://hugo-profile-2.netlify.app
      badges:
        - "Hugo"
        - "Bootstrap"
        - "Javascript"
      links:
        - icon: fab fa-github
          url: https://github.com/gurusabarish/HugoProfileV2

#Contact
contact:
  enable: true
  # title: "Custom Name"
  content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  btnName: Send
  # btnLink: mailto:your_email@gmail.com
  formspree:
    enable: true # `contact.email` value will be ignored
    formId: mgvvjjdn # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    emailCaption: "Enter your email address"
    messageCaption: "Enter your message here"
    messageRows: 5

footer:
  recentPosts:
    path: "posts"
    count: 3
    title: Recent Posts
    enable: true
    disableFeaturedImage: false
  # socialNetworks:
  #   github: https://github.com
  #   linkedin: https://linkedin.com
  #   twitter: https://twitter.com
  #   instagram: https://instagram.com
  #   facebook: https://facebook.com

# List pages like blogs and posts
listPages:
  disableFeaturedImage: false

# Single pages like blog and post
singlePages:
  socialShare: true
  readTime:
    enable: true
    content: "min read"
  scrollprogress:
    enable: true
  tags:
    openInNewTab: true

# For translations
terms:
  read: "Read"
  toc: "Table of Contents"
  copyright: "All rights reserved"
  pageNotFound: "Page not found"
  emailText: "Check out this site"
  social: Share this page

datesFormat:
  article: "Jan 2, 2006"
  articleList: "Jan 2, 2006"
  articleRecent: "Jan 2, 2006"

customScripts: # You can add custom scripts which will be added before </body> tag
#  <script type="text/javascript"><!-- any script here --></script>
  <script type="text/javascript" src="/js/codeClipboard.js"></script>
